@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI1IiwidWlkIjo1LCJpYXQiOjE3NjA3NTIyOTEsImV4cCI6MTc2MDc1OTQ5MSwiZW1haWwiOiJsdWlzMzBAZW1haWwuY29tIn0.MyVScPXHt6EYdKJekB5Lev6f6LoHl4Bqf1AU-su1Kr4

### GET /questions
GET http://localhost:8000/questionnaire/questions
Authorization: Bearer {{token}}

### POST /submit
POST http://localhost:8000/questionnaire/submit
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 5,
    "answers": [
        { "question_id": 1, "selected_value": "long" },
        { "question_id": 2, "selected_value": "buyMore" },
        { "question_id": 3, "selected_value": "advanced" },
        { "question_id": 4, "selected_value": "maximize" },
        { "question_id": 5, "selected_value": "over30" }
    ]
}

### GET /answers/
GET http://localhost:8000/questionnaire/answers/
Authorization: Bearer {{token}}

### GET /submission/
GET http://localhost:8000/questionnaire/submission/
Authorization: Bearer {{token}}

### PUT /submission/{submission_id}
PUT http://localhost:8000/questionnaire/submission/7
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "user_id": 5,
    "answers": [
        { "question_id": 1, "selected_value": "long" },
        { "question_id": 2, "selected_value": "buyMore" },
        { "question_id": 3, "selected_value": "advanced" },
        { "question_id": 4, "selected_value": "maximize" },
        { "question_id": 5, "selected_value": "over30" }
    ]
}

