@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxIiwidWlkIjoxLCJpYXQiOjE3NjM1NzkwNTEsImV4cCI6MTc2MzU4NjI1MSwiZW1haWwiOiJsdWlzQGVtYWlsLmNvbSJ9.ff9y7r3yQcN4vfcvwy5k0Gj-ugiCaH3ZhH_-RlwrV0I

### GET /recommendations
GET http://localhost:8000/recommendations/
Authorization: Bearer {{token}}

### GET /recommendations/{id}
GET http://localhost:8000/recommendations/8
Authorization: Bearer {{token}}

### POST /recommendations
POST http://localhost:8000/recommendations
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "user_id": 4,
  "crypto_id": 3,
  "risk_level": "moderado"
}

### PATCH /recommendations/{id}
PATCH http://localhost:8000/recommendations/9
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "risk_level": "baixo"
}

### POST /recommendations/recommender
POST http://localhost:8000/recommendations/recommender
Authorization: Bearer {{token}}

{
  "risk_profile": "alto"
}

### GET /recommendations/recommender
GET http://localhost:8000/recommendations/recommender
Authorization: Bearer {{token}}

### POST /recommendations/recomme
POST http://localhost:8000/recommendations/recommender
Authorization: Bearer {{token}}

{
  "risk_profile": "alto"
}

