### POST /auth/register
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "name": "Luis",
    "email": "luis@email.com",
    "password": "senha123"
}

### POST /auth/login
# @name login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "luis@email.com",
    "password": "senha123"
}

### Defina a variável {{token}} com o access_token retornado do login (VS Code REST Client permite)
@token = {{login.response.body.$.access_token}}

### UPDATE /auth/user/me
PUT http://localhost:8000/auth/user/me
Content-Type: application/json
Authorization: Bearer {{token}}

{
    "risk_profile": "moderado"
}

### GET /auth/me
GET http://localhost:8000/auth/me
Authorization: Bearer {{token}}

### DELETE /auth/user/me
DELETE http://localhost:8000/auth/user/me
Authorization: Bearer {{token}}