### POST /auth/register
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "name": "Luis",
    "email": "luis45@email.com",
    "password": "senha123"
}

### POST /auth/login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "luis45@email.com",
    "password": "senha123"
}