### POST /auth/register
POST http://localhost:8000/auth/register
Content-Type: application/json

{
    "name": "Luis",
    "email": "luis@email.com",
    "password": "senha123"
}

### POST /auth/login
POST http://localhost:8000/auth/login
Content-Type: application/json

{
    "email": "luis@email.com",
    "password": "senha123"
}

### GET /auth/user/{id}
GET http://localhost:8000/auth/user/3

### DELETE /auth/user/{id}
DELETE http://localhost:8000/auth/user/11

### UPDATE /auth/user/{id}
PUT http://localhost:8000/auth/user/10
Content-Type: application/json

{
    "risk_profile": "agressivo"
}
