name: Deploy to Render (Deploy Hook)

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency:
      group: render-deploy
      cancel-in-progress: true

    steps:
      - uses: actions/checkout@v4

      # CI rápido (opcional, mas útil)
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Install dependencies
        run: |
          pip install -U pip
          pip install -r requirements.txt

      - name: Smoke check
        run: python -c "import fastapi, sqlalchemy, jwt; print('imports ok')"

      - name: Trigger Render Deploy Hook
        env:
          RENDER_DEPLOY_HOOK_URL: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: |
          if [ -z "$RENDER_DEPLOY_HOOK_URL" ]; then
            echo "Secret RENDER_DEPLOY_HOOK_URL ausente" >&2
            exit 1
          fi
          curl -fsSL -X POST "$RENDER_DEPLOY_HOOK_URL"
          echo "Deploy disparado na Render"